version: "2"

services:
  wordpress:
    image: "chriszarate/wordpress:4.7.5"
    environment:
      PHPUNIT_TEST_DIR: "/var/www/html/wp-content/themes/vip/test"
      PHPUNIT_WP_CONTENT_LINKS: "mu-plugins"
      VIRTUAL_HOST: "${DOCKER_DEV_DOMAIN}"
      WORDPRESS_ACTIVATE_PLUGINS: "" # space-separated plugin folders relative to /wp-content/plugins/
      WORDPRESS_ACTIVATE_THEME: "mytheme" # theme folder relative to /wp-content/themes/
      WORDPRESS_CONFIG_EXTRA: "require_once( __DIR__ . '/local-config.php' );"
      WORDPRESS_SITE_TITLE: "Project"
      WORDPRESS_SITE_URL: "http://${DOCKER_DEV_DOMAIN}"
      XDEBUG_CONFIG: "remote_host=${DOCKER_LOCAL_IP} idekey=xdebug"
    depends_on:
      - "mysql"
    networks:
      - "front"
      - "back"
    volumes:
      - "./conf/php-local.ini:/usr/local/etc/php/conf.d/local.ini:ro"
      - "./conf/wp-local-config.php:/var/www/html/local-config.php:ro"
      - "./src/project:/tmp/wordpress/init-wp-content"
      - "./src/vip-go-mu-plugins:/var/www/html/wp-content/mu-plugins"
  mysql:
    image: "mariadb"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "wordpress"
      MYSQL_ROOT_PASSWORD: ""
    networks:
      - "back"
  mysql_phpunit:
    image: "mariadb"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "wordpress_phpunit"
      MYSQL_ROOT_PASSWORD: ""
    networks:
      - "back"
  proxy:
    image: "jwilder/nginx-proxy"
    ports:
      - "80:80"
    networks:
      front:
        aliases:
          - "${DOCKER_DEV_DOMAIN}"
          - "photon.${DOCKER_DEV_DOMAIN}"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./conf/nginx-proxy.conf:/etc/nginx/conf.d/proxy.conf:ro"

networks:
  front: {}
  back: {}
