version: "2"

services:
  wordpress:
    image: "chriszarate/wordpress:4.8.0"
    environment:
      PHPUNIT_TEST_DIR: "/var/www/html/wp-content/themes/vip/project"
      PHPUNIT_WP_CONTENT_LINKS: "plugins/jetpack themes/vip/plugins"
      VIRTUAL_HOST: "${DOCKER_DEV_DOMAIN}"
      WORDPRESS_ACTIVATE_PLUGINS: "jetpack log-deprecated-notices query-monitor rewrite-rules-inspector wordpress-importer"
      WORDPRESS_ACTIVATE_THEME: "vip/project"
      WORDPRESS_INSTALL_TYPE: "multisite"
      WORDPRESS_SITE_TITLE: "Project"
      WORDPRESS_SITE_URL: "http://${DOCKER_DEV_DOMAIN}"
      XDEBUG_CONFIG: "remote_host=${DOCKER_LOCAL_IP} idekey=xdebug"
    depends_on:
      - "mysql"
    networks:
      - "front"
      - "back"
    volumes:
      - "./conf/php-local.ini:/usr/local/etc/php/conf.d/local.ini:ro"
      - "./conf/wp-local-config.php:/var/www/html/local-config.php:ro"
      - "./src/test-theme:/var/www/html/wp-content/themes/vip/project"
      - "./src/vip-plugins:/var/www/html/wp-content/themes/vip/plugins"
      - "./src/vip-quickstart/www/wp-config.php:/var/www/html/wp-config.php"
      - "./src/vip-quickstart/www/config:/var/www/html/config"
      - "./src/vip-quickstart/www/wp-content:/tmp/wordpress/init-wp-content"
      - "./src/wordpress-plugins:/var/www/html/wp-content/plugins"
  photon:
    image: "chriszarate/photon:latest"
    networks:
      - "front"
  mysql:
    image: "mariadb:10.2"
    environment:
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "wordpress"
      MYSQL_PASSWORD: "wordpress"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    networks:
      - "back"
  mysql_phpunit:
    image: "mariadb:10.2"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "wordpress_phpunit"
      MYSQL_ROOT_PASSWORD: ""
    networks:
      - "back"
  proxy:
    image: "jwilder/nginx-proxy:alpine"
    ports:
      - "80:80"
    networks:
      front:
        aliases:
          - "${DOCKER_DEV_DOMAIN}"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./conf/nginx-proxy.conf:/etc/nginx/conf.d/proxy.conf:ro"
      - "./conf/nginx-proxy-wordpress.conf:/etc/nginx/vhost.d/${DOCKER_DEV_DOMAIN}_location:ro"

networks:
  front: {}
  back: {}
